# ============================================
# Ansible Inventory File
# Author: Own Ali
# Roll No: F20232661030
# Description: Defines all network devices
#              for Ansible to manage
# ============================================

[routers]
Router0 ansible_host=192.168.1.1
Router1 ansible_host=192.168.2.1
Router2 ansible_host=192.168.3.1

[routers:vars]
ansible_network_os=ios
ansible_connection=network_cli
ansible_user=admin
ansible_password=admin123
ansible_become=yes
ansible_become_method=enable
ansible_become_password=admin123
